// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viujpvwlndbyrkrahypv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdWpwdndsbmRieXJrcmFoeXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTgxMTIsImV4cCI6MjA3MDE3NDExMn0.1AgXCZ11YH7fsACQRmdo8jjUiiqkgWDBR8tHMZllGGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});